# Generated by Django 3.1.3 on 2020-11-22 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionNumber', models.CharField(max_length=12)),
                ('answer', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=53)),
                ('age', models.BigIntegerField()),
                ('gender', models.CharField(max_length=11)),
                ('weigth', models.FloatField()),
                ('mark', models.BigIntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.answer')),
            ],
        ),
    ]
