# Generated by Django 3.1.3 on 2020-11-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='answer',
        ),
        migrations.AddField(
            model_name='formdata',
            name='answer',
            field=models.ManyToManyField(to='form.Answer'),
        ),
    ]
