# Generated by Django 3.1.3 on 2020-11-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20201122_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='weigth',
            new_name='weight',
        ),
    ]
