# Generated by Django 3.1.3 on 2020-11-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20201122_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdata',
            old_name='answer',
            new_name='answers',
        ),
    ]
